Fix autodoc + Usage Notes
adafruit/Adafruit_CircuitPython_SGP30 pull request #3
Opened 2018-02-21 15:45 UTC by brentru

Added library usage notes into the README.
https://github.com/adafruit/circuitpython/issues/624

2018-02-21 23:21 UTC, kattni requested changes
Thanks for doing this! The code is not rendering in `README`. Please resolve this.

2018-02-21 23:21 UTC, kattni commented on README.rst
> +.. code:: python
This isn't rendering when I view it. If it's working for you, let me know. Otherwise please sort what the issue is - it may need to be `code-block`.

2018-02-21 23:21 UTC, kattni commented on README.rst
> +.. code:: python
Same as above.

2018-02-21 23:21 UTC, kattni commented on README.rst
> +.. code:: python
Same as above.

2018-02-21 23:21 UTC, kattni commented on README.rst
> +.. code:: python
Same as above.

2018-02-22 00:39 UTC, brentru commented on README.rst
> +.. code:: python
Thanks for the catch. Code -> code-block and an extra space rendered correctly.

2018-02-22 03:42 UTC, kattni approved these changes

2018-02-22 03:42 UTC, kattni commented
Thanks for fixing this up!

2018-02-22 03:43 UTC, merged