Add helper method to set IAQ humidity
adafruit/Adafruit_CircuitPython_SGP30 pull request #35
Opened 2022-03-20 12:09 UTC by benthorner

Most sensors only report relative humidity and temperature, so this
uses the formula in the datasheet [^1] to make calibration easier.

Notes:

- The datasheet doesn't give the origin of the formula, but it seems
to be based on Tetens Equation (to approximate pressure).

- The example in the datasheet is wrong: the output should be 11.48.

- math.exp is available in MicroPython [^2].

[^1]: https://sensirion.com/media/documents/984E0DD5/61644B8B/Sensirion_Gas_Sensors_Datasheet_SGP30.pdf
[^2]: https://docs.micropython.org/en/latest/library/math.html#math.exp

2022-03-20 17:00 UTC, tekktrik requested changes
I don't think I have the sensor to test this, but in the meantime here are the changes per the CI!  Thanks for submitting!

2022-03-20 17:00 UTC, tekktrik commented on adafruit_sgp30.py
> +        T = celcius
I would just use `celcius` instead of assigning it to `T` to save memory, and it will also fix the pylint error for variable names

2022-03-20 17:00 UTC, tekktrik commented on adafruit_sgp30.py
> +        RH = relative_humidity
I would also just use `relative_humidty` instead of reassigning.

2022-03-20 17:00 UTC, tekktrik commented on adafruit_sgp30.py
> +        Set the humidity in g/m3 for eCo2 and TVOC compensation algorithm. The absolute humidity is calculated from the temperature and relative humidity (as a percentage).
Looks like this docstring should be broken up into multiple lines:

```suggestion
        Set the humidity in g/m3 for eCo2 and TVOC compensation algorithm.
        The absolute humidity is calculated from the temperature and relative humidity
        (as a percentage).
```

2022-03-20 17:00 UTC, tekktrik commented on adafruit_sgp30.py
> +from math import exp
This import should be moved above the `I2CDevice` import

2022-03-20 17:00 UTC, tekktrik commented on adafruit_sgp30.py
> +        humidity_gramsPM3 = 216.7 * (numerator / denominator)
The variable name doesn't sit well with pylint unfortunately... Should be fine with `humidity_grams_pm3` though!

2022-03-21 08:29 UTC, benthorner commented on adafruit_sgp30.py
> +        T = celcius
Sure, amended 👍.

2022-03-21 08:31 UTC, benthorner commented on adafruit_sgp30.py
> +        Set the humidity in g/m3 for eCo2 and TVOC compensation algorithm. The absolute humidity is calculated from the temperature and relative humidity (as a percentage).
This surprised me at first, so I checked and Sphinx only makes a new line / paragraph after a double new line, so it's safe to wrap this manually - amended.

2022-03-21 08:31 UTC, benthorner commented on adafruit_sgp30.py
> +from math import exp
Done.

2022-03-21 08:33 UTC, benthorner commented on adafruit_sgp30.py
> +        humidity_gramsPM3 = 216.7 * (numerator / denominator)
Ah interesting - there's a comment disabling it above. I think your suggestion is clear enough so I've used that - that way we don't need to disable the linter in multiple places.

2022-03-21 08:36 UTC, benthorner commented
@tekktrik thanks for the speedy first look! Somehow I totally missed this repo has a CI pipeline, which I can now see is passing after fixing all the linting issues. 

I was wondering whether to add a test for the new method but thought it would be too big a step for this PR, seeing as the repo doesn't have any tests currently. What do you think?

2022-03-21 14:00 UTC, tekktrik commented
Testing isn't the norm for CircuitPython libraries, but adding an example usage to a new or existing example file would be great!  Would you mind doing that?

2022-03-21 16:31 UTC, FoamyGuy commented
Thanks for working on this @benthorner 

Echoing what tekktrik mentioned. We don't have many automated tests for the libraries. But we always do like to include an example that illustrates how to use new functionality when it gets added. 

If you're up for it please go ahead and add a small script inside of `examples/` directory that shows the new functionality you added.

2022-03-21 21:13 UTC, benthorner commented
@tekktrik @FoamyGuy no problem: https://github.com/adafruit/Adafruit_CircuitPython_SGP30/pull/35/commits/519c9087eab16c7b6e82050cea185018866ebb9d.

I thought it went best in the existing example as we're also setting baselines in there. I also double checked the example file works with the new package and my own SGP30 ✅.

2022-04-03 20:44 UTC, benthorner commented
@tekktrik @FoamyGuy any chance of this going in soon?

2022-04-03 22:35 UTC, tekktrik approved these changes
Thanks for following up!  I think this looks great, thanks for adding the example!

2022-04-03 22:35 UTC, merged